name: build-with-mpich
run-name: Build MPL with MPICH
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install build dependencies
        run: |
          sudo apt install libmpich-dev cmake ninja-build g++ libboost-test-dev
          mpichversion
      - name: Build mpl
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DMPL_BUILD_EXAMPLES=ON ..
          cmake --build . -j
      - name: Test mpl
        run: |
          cd build
          ctest
      - run: echo "This job's status is ${{ job.status }}."
